### ISSUE TITLE
corner case: gemm with a 0 dimension

### ISSUE THREAD

**Issue by nilsbecker** [mmottl/lacaml#36]
i just came across this corner case in code.
```ocaml
open Lacaml.D
let a = Mat.create 2 2
let b = lacpy ~ac:3 a
```
this gives a `b` with shape `2, 0` which seems reasonable. (however `~ac` > 3 raises)
```ocaml
let c = gemm a b
```
in the context it was used it would have been meaningful to get a matrix with shape `2,0` out. instead an exception was raised: second dimension 0. is this something within blas or does lacaml do that? in the latter case, would it make sense to allow multiplications which contain empty dimensions but are consistent dimensionally?

**Comment by nilsbecker** [comment]
what feels inconsistent is that `lacpy` allows generating empty dimensions but `gemm` does not handle them gracefully.

**Comment by nilsbecker** [comment]
aside: also `gesv a b` gives a (n empty) result.

**Comment by Chris00** [comment]
I am afraid that it is the way LAPACK works.  You may want to issue a PR adding a warning to the documentation.

**Comment by nilsbecker** [comment]
another data point: `gemm ~ar:3 a a` raises as well.

**Comment by nilsbecker** [comment]
ok, so it's just an upstream fact that `gemm` is (arguably overly) picky then?

**Comment by nilsbecker** [comment]
actually in the debugger i get this code listing 
```
394 let gemm ?m ?n ?k ?beta ?(cr = 1) ?(cc = 1) ?c
395       ?(transa = `N) ?(alpha = one) ?(ar = 1) ?(ac = 1) a
396       ?(transb = `N) ?(br = 1) ?(bc = 1) b =
397   let loc = "Lacaml.D.gemm" in
398   check_mat_empty ~loc ~mat_name:a_str ~dim1:(Mat.dim1 a) ~dim2:(Mat.dim2 a);
399   check_mat_empty ~loc ~mat_name:b_str ~dim1:(Mat.dim1 b)<|a|> ~dim2:(Mat.dim2 b);
```
in `Lacaml__Impl4_D` which suggests that empty-checking is done in the wrapper code?

**Comment by Chris00** [comment]
On 2017-12-14, nilsbecker wrote:
> 
> actually in the debugger i get this code listing
> 
> 394 let gemm ?m ?n ?k ?beta ?(cr = 1) ?(cc = 1) ?c
> 395       ?(transa = `N) ?(alpha = one) ?(ar = 1) ?(ac = 1) a
> 396       ?(transb = `N) ?(br = 1) ?(bc = 1) b =
> 397   let loc = "Lacaml.D.gemm" in
> 398   check_mat_empty ~loc ~mat_name:a_str ~dim1:(Mat.dim1 a) ~dim2:(Mat.dim2 a);
> 399   check_mat_empty ~loc ~mat_name:b_str ~dim1:(Mat.dim1 b)<|a|> ~dim2:(Mat.dim2 b);

OK, I’ll check later.

**Comment by nilsbecker** [comment]
thx!

**Comment by nilsbecker** [comment]
i handled the empty case explicitly now. 
the resulting matrix is in fact `0,0` since i do the equivalent of `gemm ~ac:3 a b`. 
and the next thing that happens is that `potrf` is called on the resulting matrix raising an exception caused by empty matrix. again, what would make sense in my context is just to return an empty matrix. (later the diagonal of that is taken (empty vector) and summed (0). so the rest of the chain of calculation would work).

**Comment by nilsbecker** [comment]
overall it seems that there are implications for a number of matrix operations with partly empty dimensions. i suspect that a consistent story is probably possible. i don't know if lapack implements such a consistent story. if it does, it might make sense to follow it. but it also seems that that might change some user code that relies on catching exceptions raised on empty matrices -- which would make for a potentially breaking change.

**Comment by nilsbecker** [comment]
e.g. the `potrf` api allows `N=0`. 

http://www.netlib.org/lapack/explore-html/d1/d7a/group__double_p_ocomputational_ga2f55f604a6003d03b5cd4a0adcfb74d6.html

**Comment by mmottl** [comment]
It seems the LAPACK `potrf` documentation and/or implementation is a little disingenuous here.  The reason why Lacaml raises an exception is, because LAPACK will return an error code if you actually pass an empty matrix.  This is because of their check of the leading dimension of `a`: `IF( lda.LT.max( 1, n ) )`.  Since the leading dimension of an empty matrix is zero, this check will always lead to an error.

This example shows how error-prone  it is to deal with empty matrices or zero-sized operations. 
 Some Lacaml-specific functions handle special cases like these more gracefully and/or mathematically appealingly, but I would not always rely on it.  It's pretty darn tricky to get these cases "right" (whatever that even means in some corner cases).

We have actually already had a discussion a while ago about this topic: https://github.com/mmottl/lacaml/issues/22

My take on this is that degenerate cases should all be handled by the user explicitly:

- If user code does not expect to deal with empty matrices or zero-sized data, it should check input arguments accordingly and raise an exception if the shape of arguments is unexpected.
- If there is a meaningful interpretation for degenerate value dimensions or operation sizes in the user program, the user has to explicitly test for these conditions and implement the correct solution.

I would not rely on BLAS/LAPACK (or Lacaml for that matter) to always behave in the expected way in such corner cases.

**Comment by nilsbecker** [comment]
i now remembered that there was a previous discussion -- i had kind of forgotten about it. so if there is already a decision taken, never mind! maybe your two points could be added to the intro of the documentation?

a quick follow up: i now started to handle the 0-dim cases explicitly. i now get the output ` ** On entry to DGEMV  parameter number  6 had an illegal value` presumably directly from lapack but no exception is raised, so i don't know where exactly that happened...

**Comment by mmottl** [comment]
I've updated the README to include more information on error handling.

What concerns `gemv`: sadly, BLAS does not provide for a return value in the API of this function (it's actually a subroutine).  This means there is no way to communicate such errors back to Lacaml.  Please feel free to submit patches if you absolutely want to catch empty values beforehand.  In that particular case the error is also related to an illegal (= zero) leading dimension.
